### ISSUE TITLE
cant compile with lpc11u68

### ISSUE THREAD

**Issue by adekto** [platformio/platform-nxplpc#9] opened 2018-03-24 14:51 UTC
lpc11u68 board wont compile
`
collect2: error: ld returned 1 exit status
*** [.pioenvs/development/firmware.elf] Error 1
`

**Comment by ivankravets** [comment] 2019-03-11 14:12
Duplicate of https://github.com/platformio/platform-nxplpc/issues/13

**Closed by ivankravets** 2019-03-11 14:12 UTC
